const sites = [
  { id: 1, label: "L’Oceano d’Or" },
  { id: 2, label: "Les Genets" },
  { id: 3, label: "Calico Park" },
];

const inventoryFrance = {
  all: [
    "Fridge freezer or fridge",
    "Microwave",
    "1 pair of scissors",
    "Washing up bowl",
    "Clothes pegs",
    "Coat hangers",
    "Dustpan/brush",
    "Long handled broom",
    "Mop and bucket",
    "Lavatory brush",
    "Fire extinguisher",
    "Waste bin",
    "Clothes aire",
    "6 Knives, forks, spoons, tea spoons",
    "2 Serving spoons",
    "1 Bread knife",
    "1 Kitchen knife",
    "1 Bread knife",
    "1 Bottle opener",
    "1 Fish slice",
    "1 Tin opener",
    "1 Wooden spoon and spatula",
    "1 Potato peeler",
    "Cafetiere",
    "1 Frying pan",
    "6 large tumblers",
    "6 small wine glasses",
    "6 dinner plates",
    "6 side plates",
    "6 small plates",
    "6 beakers",
    "6 dessert/cereal bowls",
    "1 small and large bowl",
    "Water jug",
    "3 saucepans",
    "1 kettle",
    "1 measuring jug",
    "1 glass/plastic mixing bowl",
    "1 colander",
    "1 cheese grater",
    "1 bread board",
    "6 pillows",
    "1 double blanket per person",
    "Mattress protector",
    "Parasol (for home with open veranda)",
    "Patio table",
    "6 patio chairs",
  ],
  general: [
    "Fridge freezer or fridge",
    "Microwave",
    "1 pair of scissors",
    "Washing up bowl",
    "Clothes pegs",
    "Coat hangers",
    "Dustpan/brush",
    "Long handled broom",
    "Mop and bucket",
    "Lavatory brush",
    "Fire extinguisher",
    "Waste bin",
    "Clothes aire",
  ],
  cutlery: [
    "6 Knives, forks, spoons, tea spoons",
    "2 Serving spoons",
    "1 Bread knife",
    "1 Kitchen knife",
    "1 Bread knife",
    "1 Bottle opener",
    "1 Fish slice",
    "1 Tin opener",
    "1 Wooden spoon and spatula",
    "1 Potato peeler",
    "Cafetiere",
    "1 Frying pan",
  ],
  crockery: [
    "6 large tumblers",
    "6 small wine glasses",
    "6 dinner plates",
    "6 side plates",
    "6 small plates",
    "6 beakers",
    "6 dessert/cereal bowls",
    "1 small and large bowl",
    "Water jug",
  ],
  cookingEquipment: [
    "3 saucepans",
    "1 kettle",
    "1 measuring jug",
    "1 glass/plastic mixing bowl",
    "1 colander",
    "1 cheese grater",
    "1 bread board",
  ],
  bedding: ["6 pillows", "1 double blanket per person", "Mattress protector"],
  outside: [
    "Parasol (for home with open veranda)",
    "Patio table",
    "6 patio chairs",
  ],
};

const inventoryPortugal = {
  all: [
    "Fridge freezer or fridge",
    "Microwave",
    "1 pair of scissors",
    "Washing up bowl",
    "Clothes pegs",
    "Coat hangers",
    "Dustpan/brush",
    "Long handled broom",
    "Mop and bucket",
    "Lavatory brush",
    "Fire extinguisher",
    "Waste bin",
    "Clothes aire",
    "6 Knives, forks, spoons, tea spoons",
    "2 Serving spoons",
    "1 Bread knife",
    "1 Kitchen knife",
    "1 Bread knife",
    "1 Bottle opener",
    "1 Fish slice",
    "1 Tin opener",
    "1 Wooden spoon and spatula",
    "1 Potato peeler",
    "Cafetiere",
    "1 Frying pan",
    "6 large tumblers",
    "6 small wine glasses",
    "6 dinner plates",
    "6 side plates",
    "6 small plates",
    "6 beakers",
    "6 dessert/cereal bowls",
    "1 small and large bowl",
    "Water jug",
    "3 saucepans",
    "1 kettle",
    "1 measuring jug",
    "1 glass/plastic mixing bowl",
    "1 colander",
    "1 cheese grater",
    "1 bread board",
    "6 pillows",
    "1 double blanket per person",
    "Mattress protector",
    "Parasol (for home with open veranda)",
    "Patio table",
    "6 patio chairs",
  ],
  general: [
    "Air conditioning",
    "Flat screen TV and DVD player with English channels",
    "Washing machine",
    "All bed linen and towels provided",
    "Fridge freezer or fridge",
    "Microwave",
    "1 pair of scissors",
    "Washing up bowl",
    "Clothes pegs",
    "Coat hangers",
    "Dustpan/brush",
    "Long handled broom",
    "Mop and bucket",
    "Lavatory brush",
    "Fire extinguisher",
    "Waste bin",
    "Clothes airer",
  ],
  cutlery: [
    "6 Knives, forks, spoons, tea spoons",
    "2 Serving spoons",
    "1 Bread knife",
    "1 Kitchen knife",
    "1 Bread knife",
    "1 Bottle opener",
    "1 Fish slice",
    "1 Tin opener",
    "1 Wooden spoon and spatula",
    "1 Potato peeler",
    "Cafetiere",
    "1 Frying pan",
  ],
  crockery: [
    "6 large tumblers",
    "6 small wine glasses",
    "6 dinner plates",
    "6 side plates",
    "6 small plates",
    "6 beakers",
    "6 dessert/cereal bowls",
    "1 small and large bowl",
    "Water jug",
  ],
  cookingEquipment: [
    "3 saucepans",
    "1 kettle",
    "1 measuring jug",
    "1 glass/plastic mixing bowl",
    "1 colander",
    "1 cheese grater",
    "1 bread board",
  ],
  outside: [
    "Parasol (for home with open veranda)",
    "Patio table",
    "6 patio chairs",
  ],
};

const faqQuestionsAnswers = [
  {
    "What are your arrival times?":
      "Arrival times are strictly from 4pm onwards.",
  },
  {
    "What are your departure times?":
      "Clients must leave the home before 10am.",
  },
  {
    "Should I book linen in advance?":
      "Linen must be booked at least 6 weeks before the start of your holiday. Please see Prices Page for details and prices.",
  },
  {
    "Are pets allowed?":
      "We do allow a well behaved pet in designated homes. Your dog must be kept on a lead at all times within the campsite, and must not be left unattended in the home. This is a strict campsite policy.",
  },
  {
    "Is Satellite TV available?":
      "We do have a limited number of homes where you can hire Satellite TV with English channels. Please ask at time of booking.",
  },
  {
    "Are deposits refundable?":
      "Your deposit is non-refundable should you cancel your holiday.",
  },
  {
    "When is balance due?":
      "The balance of your holiday payment is due 10 weeks before the holiday start date. We accept all major credit and debit card payments. You can also arrange to pay for your holiday in instalments.",
  },
  {
    "What is your cancellation policy?":
      "In the event of a cancellation, refunds of amounts paid (less the deposit) will be made if Quest en France Holidays are able to re-let the \"Mobile Home\", and any expenses or losses incurred in so doing will be deducted from the refundable amount. The Client is strongly recommended to arrange a comprehensive travel insurance policy (including cancellation cover) and to have full cover for the party’s personal belongings, public liability etc, since these are not covered by the Owner's insurance.",
  },
];

const config = {
  sites,
  inventoryFrance,
  inventoryPortugal,
  faqQuestionsAnswers,
};

export default config;
