# Generated by Django 2.2.9 on 2020-04-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='fridge_freezer',
            new_name='fridge',
        ),
        migrations.AddField(
            model_name='home',
            name='tv',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='gas_tails',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='pull_out_bed',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
