# Generated by Django 2.2.9 on 2021-03-09 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_auto_20200708_2052'),
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='fridge',
        ),
        migrations.RemoveField(
            model_name='home',
            name='gas_tails',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
        migrations.RemoveField(
            model_name='home',
            name='tow_bars',
        ),
        migrations.AddField(
            model_name='home',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homes', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='home',
            name='tv',
            field=models.SmallIntegerField(),
        ),
    ]
