# Generated by Django 2.2.9 on 2021-03-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_auto_20210309_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='pull_out_bed',
            field=models.SmallIntegerField(),
        ),
    ]
