# Generated by Django 2.2.9 on 2020-04-03 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('homes', '0002_auto_20200403_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homes', to='sites.Site'),
        ),
    ]
