# Generated by Django 2.2.9 on 2020-05-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_homeimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeImages',
        ),
    ]
