# Generated by Django 2.2.9 on 2020-04-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_home_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='plot',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='tow_bars',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
