# Generated by Django 2.2.9 on 2020-05-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20200503_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='images',
            new_name='gallery_images',
        ),
        migrations.AddField(
            model_name='site',
            name='main_image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
