# Generated by Django 2.2.9 on 2020-05-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20200512_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='area',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
