# Generated by Django 2.2.9 on 2020-05-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_site_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
