# Generated by Django 2.2.9 on 2020-05-19 19:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_auto_20200514_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='long_description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5000), size=None),
        ),
    ]
