# Generated by Django 2.2.9 on 2020-05-19 20:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_auto_20200519_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='facilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), size=None),
        ),
    ]
