# Generated by Django 2.2.9 on 2020-07-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_auto_20200519_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongDescriptionParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='long_description_paragraph', to='sites.Site')),
            ],
        ),
    ]
