# Generated by Django 2.2.9 on 2020-07-08 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_longdescriptionparagraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longdescriptionparagraph',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='long_description_paragraphs', to='sites.Site'),
        ),
    ]
