# Generated by Django 2.2.9 on 2020-05-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.SmallIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('additional_comments', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='bookings.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Ferry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_route', models.CharField(max_length=100)),
                ('outbound_date', models.DateField()),
                ('inbound_route', models.CharField(max_length=100)),
                ('inbound_date', models.DateField()),
                ('number_of_adults', models.SmallIntegerField()),
                ('number_of_children', models.SmallIntegerField()),
                ('number_of_infants', models.SmallIntegerField()),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_height', models.CharField(max_length=100)),
                ('roof_box', models.CharField(max_length=3)),
                ('bike_rack_on_top', models.CharField(max_length=3)),
                ('bike_rack_on_rear', models.CharField(max_length=3)),
                ('trailor', models.CharField(max_length=3)),
                ('trailer_length', models.CharField(blank=True, max_length=100)),
                ('additional_comments', models.CharField(blank=True, max_length=10000)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ferry_quote', to='bookings.Booking')),
            ],
        ),
    ]
