# Generated by Django 2.2.9 on 2020-04-08 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_route', models.CharField(max_length=100)),
                ('outbound_date', models.IntegerField()),
                ('inbound_route', models.CharField(max_length=100)),
                ('inbound_date', models.IntegerField()),
                ('number_of_adults', models.SmallIntegerField()),
                ('number_of_children', models.SmallIntegerField()),
                ('number_of_infants', models.SmallIntegerField()),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_height', models.CharField(max_length=100)),
                ('roof_box', models.CharField(max_length=3)),
                ('bike_rack_on_top', models.CharField(max_length=3)),
                ('bike_rack_on_rear', models.CharField(max_length=3)),
                ('trailor', models.CharField(max_length=3)),
                ('trailer_length', models.CharField(blank=True, max_length=100)),
                ('additional_comments', models.CharField(blank=True, max_length=10000)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ferry_quote', to='bookings.Booking')),
            ],
        ),
        migrations.DeleteModel(
            name='FerryQuote',
        ),
    ]
