# Generated by Django 2.2.9 on 2020-04-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20200408_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.CharField(max_length=14),
        ),
    ]
