# Generated by Django 2.2.9 on 2020-05-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20200414_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.CharField(max_length=8),
        ),
    ]
