# Generated by Django 2.2.9 on 2021-05-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20200503_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='additional_comments',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
