# Generated by Django 2.2.9 on 2021-05-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20210521_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripeCustomerId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
