# Generated by Django 2.2.9 on 2021-05-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_stripecustomerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='kids',
            field=models.SmallIntegerField(null=True),
        ),
    ]
