# Generated by Django 2.2.9 on 2021-05-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20210524_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.FloatField(),
        ),
    ]
