# Generated by Django 2.2.9 on 2020-05-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_images', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeImages',
            new_name='HomeImage',
        ),
    ]
