# Generated by Django 2.2.9 on 2020-07-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_images', '0002_auto_20200517_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeimage',
            name='home_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
